cabal-version:   3.0
name:            flattr
version:         0.1.0.0
synopsis:        Flattened Attributes
license:         BSD-3-Clause
license-file:    LICENSE
author:          David Brenton Allen
maintainer:      david.allen@columnzero.com
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

library
  import:             warnings
  exposed-modules:
    Flattr
    Path
    Types
    ValueBuilder

  build-depends:
    , aeson
    , base                  ^>=4.18.0.0
    , bytestring
    , containers
    , text
    , unordered-containers
    , vector
    , yaml

  hs-source-dirs:     app
  default-language:   Haskell2010
  default-extensions:
    DeriveGeneric
    LambdaCase
    OverloadedStrings

executable flattr
  import:           warnings
  main-is:          Main.hs
  hs-source-dirs:   app
  build-depends:
    , base    ^>=4.18.0.0
    , flattr

  default-language: Haskell2010

test-suite tests
  type:               exitcode-stdio-1.0
  main-is:            Main.hs
  other-modules:
    FlattrTests
    ValueBuilderTests

  hs-source-dirs:     tests
  build-depends:
    , aeson
    , base        ^>=4.18.0.0
    , call-stack  >=0.3.0
    , containers
    , flattr
    , HUnit

  default-extensions: OverloadedStrings
  default-language:   Haskell2010
